### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by amiangshu** [SIU-CS/J-JAM-production#99]
@akohli96 @markiragoldberg @foxstrunk @pelikenesis 

Installation failed. I do have included the secret keys in my  .bashrc

bosu@CS-BOSU-SERVER:~/CS435/J-JAM-production$ sudo python mhapsite/manage.py makemigrations
None None None
Traceback (most recent call last):
  File "mhapsite/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 10, in <module>
    from django.db.migrations.autodetector import MigrationAutodetector
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/autodetector.py", line 13, in <module>
    from django.db.migrations.questioner import MigrationQuestioner
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/questioner.py", line 12, in <module>
    from .loader import MigrationLoader
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 12, in <module>
    class MigrationRecorder(object):
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
    class Migration(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 27, in Migration
    app = models.CharField(max_length=255)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1043, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 166, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 116, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

**Comment by markiragoldberg** [comment]
The message says SECRET_KEY but the variable it looks for is SECRET. I will fix this.

**Comment by markiragoldberg** [comment]
The install should work now (unless you changed the environment variable to SECRET on your end, in which case change it back to SECRET_KEY).

**Comment by amiangshu** [comment]
Did not fix the issue. Could you please verify if the installation and run instructions are correct?

**Comment by akohli96** [comment]
I cloned it and followed the instruction exactly as on our readme.

Travis passed as well.

Please close the issue if it works otherwise let us know Dr. Bosu @amiangshu

**Comment by amiangshu** [comment]
It works now. You also should include what's the default url. I put 127.0.0.1:8000 first but then it was coming as page not found. After few guesses, I put "mhap" and it came. Looks good. BTW, what's the purpose of the bot? It always replies me with "I am not intelligent.. ...."

**Comment by amiangshu** [comment]
I just saw, it can respond only to help or quote.

**Comment by akohli96** [comment]
Right, our bot for the time being serves an API fetcher to get help resources and quotes.
